---
version: '2'
services:
  bubbleupnp-server:
    restart: 'no'
    build:
      context: ./
      args:
        site_url: ${site_url}
        pkg: ${pkg}
    image: ${REGISTRY_LOCAL}/${NAME}:${VER}
    network_mode: "host"
    volumes:
      - "${PWD}/data/configuration.xml:/opt/bubbleupnpserver/configuration.xml:\
        rw"
      # for test
      #command: /bin/sh -c 'while true; do echo dummy; sleep 600; done'
